# $Id: Makefile,v 1.1 2001/12/12 23:44:45 jsiegel Exp $
# Makefile for Maple Bus drivers

O_TARGET	:= maplebus.o

export-objs	:= maple.o

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_MAPLE)		+= maple.o

include $(TOPDIR)/Rules.make
