/* DO NOT TOUCH, AUTOGENERATED BY OFFSET.C */

#ifndef _MIPS_OFFSET_H
#define _MIPS_OFFSET_H

/* MIPS pt_regs offsets. */
#define PT_R0     32
#define PT_R1     48
#define PT_R2     64
#define PT_R3     80
#define PT_R4     96
#define PT_R5     112
#define PT_R6     128
#define PT_R7     144
#define PT_R8     160
#define PT_R9     176
#define PT_R10    192
#define PT_R11    208
#define PT_R12    224
#define PT_R13    240
#define PT_R14    256
#define PT_R15    272
#define PT_R16    288
#define PT_R17    304
#define PT_R18    320
#define PT_R19    336
#define PT_R20    352
#define PT_R21    368
#define PT_R22    384
#define PT_R23    400
#define PT_R24    416
#define PT_R25    432
#define PT_R26    448
#define PT_R27    464
#define PT_R28    480
#define PT_R29    496
#define PT_R30    512
#define PT_R31    528
#define PT_LO     544
#define PT_HI     560
#define PT_SA     576
#define PT_EPC    580
#define PT_BVADDR 584
#define PT_STATUS 588
#define PT_CAUSE  592
#define PT_SIZE   608

/* MIPS task_struct offsets. */
#define TASK_STATE         0
#define TASK_FLAGS         100
#define TASK_SIGPENDING    8
#define TASK_NEED_RESCHED  20
#define TASK_PTRACE        24
#define TASK_COUNTER       32
#define TASK_NICE          36
#define TASK_MM            44
#define TASK_PID           128
#define TASK_STRUCT_SIZE   1064

/* MIPS specific thread_struct offsets. */
#define THREAD_REG16   624
#define THREAD_REG17   628
#define THREAD_REG18   632
#define THREAD_REG19   636
#define THREAD_REG20   640
#define THREAD_REG21   644
#define THREAD_REG22   648
#define THREAD_REG23   652
#define THREAD_REG29   656
#define THREAD_REG30   660
#define THREAD_REG31   664
#define THREAD_STATUS  668
#define THREAD_FPU     672
#define THREAD_FPU_ACC 932
#define THREAD_BVADDR  936
#define THREAD_BUADDR  940
#define THREAD_ECODE   944
#define THREAD_TRAPNO  948
#define THREAD_MFLAGS  952
#define THREAD_CURDS   956
#define THREAD_TRAMP   960
#define THREAD_OLDCTX  964

/* Linux mm_struct offsets. */
#define MM_USERS      16
#define MM_PGD        12
#define MM_CONTEXT    128

/* Linux sigcontext offsets. */
#define SC_REGS       16
#define SC_FPREGS     528
#define SC_MDHI       816
#define SC_MDLO       832
#define SC_SA         848
#define SC_FP_ACC     852
#define SC_PC         8
#define SC_STATUS     4
#define SC_OWNEDFP    784
#define SC_FPC_CSR    788
#define SC_FPC_EIR    792
#define SC_CAUSE      856
#define SC_BADVADDR   860

#endif /* !(_MIPS_OFFSET_H) */
